# MongoDB datasource
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=suchika_health

# Quarkus
quarkus.arc.exclude-types=com.suchika.health.adapters.DatabaseMigrator

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=filesystem:../../../../../../flyway/health

# OpenAPI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
