/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/accounts": {
    /**
     * List all accounts
     * @description Returns accounts optionally filtered by account_type, is_active, and profile_id. Follows AIP-132.
     */
    get: operations["listAccounts"];
    /**
     * Create an account
     * @description Creates a new financial account scoped to a profile. Follows AIP-133.
     */
    post: operations["createAccount"];
  };
  "/v1/accounts/{accountId}": {
    /**
     * Get an account
     * @description Follows AIP-131.
     */
    get: operations["getAccount"];
    /**
     * Deactivate an account
     * @description Soft-deletes an account (is_active = false). Accounts with transactions cannot be deactivated. Follows AIP-135.
     */
    delete: operations["deactivateAccount"];
    /**
     * Update an account
     * @description Partially updates an account. Only provided fields are updated. account_type and institution_name are immutable after creation. Follows AIP-134.
     */
    patch: operations["updateAccount"];
  };
  "/v1/accounts/{accountId}/balance": {
    /**
     * Get the computed current balance for an account
     * @description opening_balance + SUM(CREDIT) - SUM(DEBIT) over the account's full transaction ledger (Epic 8 Phase 1, Bug 2 fix).
     */
    get: operations["getAccountBalance"];
  };
  "/v1/accounts/{accountId}/amortization": {
    /**
     * Get current amortization summary for a loan account
     * @description Epic 8 Phase 3. Requires loan metadata set via PATCH /classification. Only valid for HOME_LOAN, CAR_LOAN, PERSONAL_LOAN accounts.
     */
    get: operations["getAmortization"];
  };
  "/v1/accounts/{accountId}/classification": {
    /**
     * Set Epic 8 classification metadata on an account
     * @description Merges category, liquidity_tier, purpose_tag, and joint_owners (ADR-016 Decision 2) into the account's existing metadata map. All fields optional.
     */
    patch: operations["updateAccountClassification"];
  };
  "/v1/accounts/{accountId}/transactions": {
    /**
     * List transactions for an account
     * @description Returns transactions for the given account, optionally filtered by date range and transaction type. Follows AIP-132.
     */
    get: operations["listTransactions"];
    /**
     * Manually enter a single transaction
     * @description Creates a manually-entered transaction without a CSV upload (Q7). Tagged with metadata.source = "MANUAL". No dedup check.
     */
    post: operations["createTransaction"];
  };
  "/v1/accounts/{accountId}/transactions/{txnId}": {
    /**
     * Get a transaction
     * @description Follows AIP-131.
     */
    get: operations["getTransaction"];
  };
  "/v1/accounts/{accountId}/transactions/{txnId}/category": {
    /**
     * Set the expense category on a single transaction
     * @description Epic 8 Phase 2 manual categorization (Use Case 8.3, Q24).
     */
    patch: operations["updateTransactionCategory"];
  };
  "/v1/accounts/{accountId}/transactions/category": {
    /**
     * Set the expense category on a caller-selected list of transactions
     * @description Epic 8 Phase 2 bulk-tag-by-selection (Use Case 8.3, Q24 resolution — not a rules engine). Tags every transaction_id in the request with the same category.
     */
    patch: operations["bulkUpdateTransactionCategory"];
  };
  "/v1/accounts/{accountId}/uploads": {
    /**
     * List uploads for an account
     * @description Follows AIP-132.
     */
    get: operations["listUploads"];
    /**
     * Upload a CSV bank statement
     * @description Parses and imports a CSV bank statement for the given account. Returns a statement upload record with status. Follows AIP-133.
     */
    post: operations["uploadStatement"];
  };
  "/v1/accounts/{accountId}/uploads/{uploadId}/errors": {
    /** Get structured parse errors for a failed upload */
    get: operations["getUploadErrors"];
  };
  "/v1/accounts/{accountId}/uploads/{uploadId}": {
    /**
     * Rollback a statement upload
     * @description Deletes all transactions imported by this upload and removes the upload record. Follows AIP-135.
     */
    delete: operations["rollbackUpload"];
  };
  "/v1/physical-assets": {
    /**
     * List all physical assets
     * @description Returns physical assets (vehicles, etc.) optionally filtered by asset_type, is_active, and profile_id. Follows AIP-132.
     */
    get: operations["listPhysicalAssets"];
    /**
     * Register a physical asset
     * @description Creates a new physical asset scoped to a profile. registration_number must be unique. Follows AIP-133.
     */
    post: operations["createPhysicalAsset"];
  };
  "/v1/physical-assets/{assetId}": {
    /**
     * Get a physical asset
     * @description Follows AIP-131.
     */
    get: operations["getPhysicalAsset"];
    /**
     * Deactivate a physical asset
     * @description Soft-deletes a physical asset (is_active = false). Follows AIP-135.
     */
    delete: operations["deactivatePhysicalAsset"];
    /**
     * Update a physical asset
     * @description Partially updates a physical asset. Only provided fields are updated. metadata is merged into the existing map, never replaced wholesale. asset_type and registration_number are immutable after creation. Follows AIP-134.
     */
    patch: operations["updatePhysicalAsset"];
  };
  "/v1/household/calendar-events": {
    /** List calendar events for a profile */
    get: operations["listCalendarEvents"];
    /** Create a calendar event */
    post: operations["createCalendarEvent"];
  };
  "/v1/household/calendar-events/{id}": {
    /** Get a calendar event */
    get: operations["getCalendarEvent"];
    /** Delete a calendar event */
    delete: operations["deleteCalendarEvent"];
    /** Update a calendar event */
    patch: operations["updateCalendarEvent"];
  };
  "/v1/household/inventory-items": {
    /** List inventory items for a profile */
    get: operations["listInventoryItems"];
    /** Add an inventory item */
    post: operations["createInventoryItem"];
  };
  "/v1/household/inventory-items/{id}": {
    /** Get an inventory item */
    get: operations["getInventoryItem"];
    /**
     * Update an inventory item
     * @description Full edit of an inventory item, including toggling is_consumed ("used in a calculation," not "physically used up"). Items are never deleted or expired.
     */
    put: operations["updateInventoryItem"];
    /** Delete an inventory item */
    delete: operations["deleteInventoryItem"];
  };
  "/v1/household/goals": {
    /** List financial goals for a profile */
    get: operations["listGoals"];
    /** Create a financial goal */
    post: operations["createGoal"];
  };
  "/v1/household/goals/{id}": {
    /** Get a goal */
    get: operations["getGoal"];
    /** Delete a goal */
    delete: operations["deleteGoal"];
    /** Update a goal */
    patch: operations["updateGoal"];
  };
  "/v1/projections/refresh/{profileId}": {
    /**
     * Trigger full projection refresh for a profile
     * @description Calls each domain service, computes cross-domain metrics, and writes results to projections.dashboard_snapshot via UPSERT. Synchronous — returns 200 once all snapshots are written.
     */
    post: operations["refreshProjections"];
  };
  "/v1/projections/dashboard/{profileId}": {
    /**
     * Read pre-computed dashboard snapshots for a profile
     * @description Reads from projections.dashboard_snapshot — instant response with no re-computation. Returns an empty snapshots list if no refresh has run.
     */
    get: operations["getDashboard"];
  };
  "/v1/vacation-planner/budget-check": {
    /**
     * Check trip budget against liquid savings and vehicle compliance against trip dates
     * @description Reads the profile's already-computed WEALTH_LIQUIDITY_TIERS_FAMILY snapshot (refresh the dashboard first if it does not exist yet) and compares the LIQUID tier balance to the trip cost. Separately checks every active VEHICLE physical asset's PUC/insurance expiry (read directly from JSONB metadata) against the trip end date.
     */
    post: operations["vacationPlannerBudgetCheck"];
  };
  "/v1/admins": {
    /** List all admins */
    get: operations["listAdmins"];
    /** Create an admin */
    post: operations["createAdmin"];
  };
  "/v1/admins/{adminId}": {
    /** Get an admin by id */
    get: operations["getAdmin"];
  };
  "/v1/admins/{adminId}/policy": {
    /**
     * Merge household policy settings (includes the one-time setup_completed flag)
     * @description Merges the provided keys into the admin's existing policy_settings map. Keys with a null value are ignored (existing value is preserved).
     */
    patch: operations["updateAdminPolicySettings"];
  };
  "/v1/profiles": {
    /** List profiles scoped to an admin */
    get: operations["listProfiles"];
    /** Create a household member profile */
    post: operations["createProfile"];
  };
  "/v1/profiles/{profileId}": {
    /** Get a profile by id */
    get: operations["getProfile"];
    /** Deactivate a profile (soft delete) */
    delete: operations["deactivateProfile"];
    /**
     * Update a profile
     * @description Partial update. Only email_address, gender, blood_type, and is_active are mutable — full_name, dob, relation_to_admin, admin_id are immutable.
     */
    patch: operations["updateProfile"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AdminResponse: {
      /** @example admins/550e8400-e29b-41d4-a716-446655440000 */
      name?: string;
      /** Format: uuid */
      admin_id?: string;
      display_name?: string;
      /** Format: email */
      email_address?: string;
      is_active?: boolean;
      /** Format: date-time */
      created_at?: string;
      /** @description Household-level policy thresholds plus the one-time setup_completed flag. All keys optional. */
      policy_settings?: {
        [key: string]: string;
      };
    };
    ListAdminsResponse: {
      admins?: components["schemas"]["AdminResponse"][];
    };
    CreateAdminRequest: {
      display_name: string;
      /** Format: email */
      email_address?: string;
    };
    UpdateAdminPolicyRequest: {
      /** @description Keys to merge into the existing policy_settings map. A null value for a key leaves the existing value unchanged. */
      policy_settings: {
        [key: string]: string | null;
      };
    };
    ProfileResponse: {
      /** @example profiles/550e8400-e29b-41d4-a716-446655440000 */
      name?: string;
      /** Format: uuid */
      profile_id?: string;
      /** Format: uuid */
      admin_id?: string;
      full_name?: string;
      /** Format: date */
      dob?: string;
      /** @enum {string} */
      relation_to_admin?: "SELF" | "SPOUSE" | "CHILD" | "PARENT" | "SIBLING" | "OTHER";
      /** Format: email */
      email_address?: string;
      /** @enum {string} */
      gender?: "MALE" | "FEMALE" | "OTHER" | "PREFER_NOT_TO_SAY";
      /** @enum {string} */
      blood_type?: "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-";
      is_active?: boolean;
      /** Format: date-time */
      created_at?: string;
    };
    ListProfilesResponse: {
      profiles?: components["schemas"]["ProfileResponse"][];
    };
    CreateProfileRequest: {
      /** Format: uuid */
      admin_id: string;
      full_name: string;
      /** Format: date */
      dob: string;
      /** @enum {string} */
      relation_to_admin: "SELF" | "SPOUSE" | "CHILD" | "PARENT" | "SIBLING" | "OTHER";
      /** Format: email */
      email_address?: string;
      /** @enum {string} */
      gender?: "MALE" | "FEMALE" | "OTHER" | "PREFER_NOT_TO_SAY";
      /** @enum {string} */
      blood_type?: "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-";
    };
    UpdateProfileRequest: {
      /** Format: email */
      email_address?: string;
      /** @enum {string} */
      gender?: "MALE" | "FEMALE" | "OTHER" | "PREFER_NOT_TO_SAY";
      /** @enum {string} */
      blood_type?: "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-";
      is_active?: boolean;
    };
    DashboardSnapshotDto: {
      /** Format: uuid */
      profile_id?: string;
      /** @description e.g. WEALTH_NET_WORTH, HEALTH_VITALS_SUMMARY */
      snapshot_key?: string;
      /** @description Raw JSON string — shape depends on snapshot_key */
      payload?: string;
      /** Format: date-time */
      calculated_at?: string;
    };
    DashboardResponse: {
      snapshots?: components["schemas"]["DashboardSnapshotDto"][];
    };
    VacationPlannerRequest: {
      /** Format: double */
      trip_cost?: number;
      /** Format: date */
      trip_start_date?: string;
      /** Format: date */
      trip_end_date: string;
    };
    VacationPlannerBudgetCheck: {
      /** @enum {string} */
      status?: "PASS" | "WARNING" | "UNAVAILABLE";
      /** Format: double */
      liquid_savings?: number;
      /** Format: double */
      trip_cost?: number;
      /** Format: double */
      shortfall?: number;
      /** @description Present only when status is UNAVAILABLE */
      message?: string;
    };
    VacationPlannerComplianceIssue: {
      /** Format: uuid */
      asset_id?: string;
      asset_name?: string;
      /** @enum {string} */
      issue_type?: "PUC_EXPIRED" | "INSURANCE_EXPIRED";
      /** Format: date */
      expiry_date?: string;
    };
    VacationPlannerAssetCompliance: {
      /** @enum {string} */
      status?: "PASS" | "WARNING";
      issues?: components["schemas"]["VacationPlannerComplianceIssue"][];
    };
    VacationPlannerResponse: {
      budget_check?: components["schemas"]["VacationPlannerBudgetCheck"];
      asset_compliance?: components["schemas"]["VacationPlannerAssetCompliance"];
    };
    /** @enum {string} */
    AccountType: "SAVINGS" | "CURRENT" | "CREDIT_CARD" | "HOME_LOAN" | "PERSONAL_LOAN" | "CAR_LOAN" | "MUTUAL_FUND" | "NPS" | "PPF" | "FD";
    /** @enum {string} */
    TransactionType: "CREDIT" | "DEBIT";
    /** @enum {string} */
    UploadStatus: "PENDING" | "COMPLETED" | "FAILED";
    /** @enum {string} */
    AssetType: "VEHICLE";
    /** @enum {string} */
    RegistrationType: "PRIVATE" | "COMMERCIAL" | "GOVERNMENT" | "BH_SERIES";
    AccountResponse: {
      /** Format: uuid */
      account_id?: string;
      account_name?: string;
      account_type?: components["schemas"]["AccountType"];
      institution_name?: string;
      /** Format: double */
      opening_balance?: number;
      /** Format: double */
      credit_limit?: number | null;
      /** Format: double */
      interest_rate?: number | null;
      /** Format: double */
      emi_amount?: number | null;
      is_active?: boolean;
      /** Format: date-time */
      created_at?: string;
      /** @description Epic 8 classification metadata (category, liquidity_tier, purpose_tag, joint_owners). joint_owners is a comma-joined list of co-owner profile_id strings (ADR-016 Decision 2) — attribution/display only. */
      metadata?: {
        [key: string]: string;
      };
    };
    AccountBalanceResponse: {
      /** Format: uuid */
      account_id?: string;
      /** Format: double */
      opening_balance?: number;
      /** Format: double */
      total_credits?: number;
      /** Format: double */
      total_debits?: number;
      /** Format: double */
      current_balance?: number;
    };
    /** @description All fields optional. Only provided keys are merged into metadata. */
    UpdateAccountClassificationRequest: {
      category?: string;
      liquidity_tier?: string;
      purpose_tag?: string;
      /** @description Co-owner profile_id strings (ADR-016 Decision 2). */
      joint_owners?: string[] | null;
      loan_original_principal?: string | null;
      loan_start_date?: string | null;
      loan_tenure_months?: string | null;
      linked_offset_account_id?: string | null;
    };
    /** @description Computed amortization snapshot for a loan account. Epic 8 Phase 3. */
    AmortizationSummaryResponse: {
      /** Format: double */
      monthly_emi?: number;
      /** Format: double */
      outstanding_balance?: number;
      remaining_months?: number;
      /** Format: double */
      total_interest_remaining?: number;
      /** Format: double */
      principal_paid?: number;
      /** Format: double */
      interest_paid?: number;
    };
    CreateAccountRequest: {
      account_name: string;
      account_type: components["schemas"]["AccountType"];
      institution_name: string;
      /**
       * Format: double
       * @default 0
       */
      opening_balance?: number;
      /** Format: double */
      credit_limit?: number | null;
      /** Format: double */
      interest_rate?: number | null;
      /** Format: double */
      emi_amount?: number | null;
    };
    /** @description All fields optional. Only provided fields are updated. */
    UpdateAccountRequest: {
      account_name?: string;
      /** Format: double */
      opening_balance?: number;
      /** Format: double */
      credit_limit?: number | null;
      /** Format: double */
      interest_rate?: number | null;
      /** Format: double */
      emi_amount?: number | null;
      is_active?: boolean;
    };
    ListAccountsResponse: {
      accounts?: components["schemas"]["AccountResponse"][];
      next_page_token?: string | null;
      total_size?: number;
    };
    PhysicalAssetResponse: {
      /** Format: uuid */
      asset_id?: string;
      asset_name?: string;
      asset_type?: components["schemas"]["AssetType"];
      make?: string;
      model?: string;
      registration_number?: string;
      registration_type?: components["schemas"]["RegistrationType"];
      is_active?: boolean;
      /** Format: date-time */
      created_at?: string;
      /** @description Compliance deadlines and optional vehicle details (puc_expiry, insurance_expiry, insurance_provider, road_tax_expiry, etc.). */
      metadata?: {
        [key: string]: string;
      };
    };
    CreatePhysicalAssetRequest: {
      asset_name: string;
      asset_type: components["schemas"]["AssetType"];
      make: string;
      model: string;
      registration_number: string;
      registration_type: components["schemas"]["RegistrationType"];
    };
    /** @description All fields optional. Only provided fields are updated. metadata is merged into the existing map, never replaced wholesale. */
    UpdatePhysicalAssetRequest: {
      asset_name?: string;
      make?: string;
      model?: string;
      metadata?: {
        [key: string]: string;
      };
      is_active?: boolean;
    };
    ListPhysicalAssetsResponse: {
      physical_assets?: components["schemas"]["PhysicalAssetResponse"][];
      total_size?: number;
    };
    TransactionResponse: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      account_id?: string;
      /** Format: uuid */
      upload_id?: string | null;
      /** Format: date */
      txn_date?: string;
      /** Format: double */
      amount?: number;
      txn_type?: components["schemas"]["TransactionType"];
      description?: string | null;
      /** Format: date-time */
      created_at?: string;
      /** @description Epic 8 Phase 2 classification metadata (category). */
      metadata?: {
        [key: string]: string;
      };
    };
    ListTransactionsResponse: {
      transactions?: components["schemas"]["TransactionResponse"][];
      /** Format: int64 */
      total_size?: number;
      page?: number;
      size?: number;
    };
    /**
     * @description Epic 8 Phase 2 hardcoded expense category enum (manual tagging only).
     * @enum {string}
     */
    ExpenseCategory: "HOUSEHOLD_CORE" | "CHILD_RELATED" | "MAINTENANCE" | "DISCRETIONARY" | "UNCATEGORIZED";
    CreateTransactionRequest: {
      /**
       * Format: date
       * @example 2026-07-01
       */
      txn_date: string;
      /**
       * Format: double
       * @description Must be positive
       */
      amount: number;
      txn_type: components["schemas"]["TransactionType"];
      description?: string;
    };
    UpdateTransactionCategoryRequest: {
      category: components["schemas"]["ExpenseCategory"];
    };
    BulkUpdateTransactionCategoryRequest: {
      transaction_ids: string[];
      category: components["schemas"]["ExpenseCategory"];
    };
    UploadStatementRequest: {
      file_name: string;
      csv_content: string;
    };
    SkippedTransactionDto: {
      /** Format: date */
      txn_date?: string;
      /** Format: double */
      amount?: number;
      description?: string;
    };
    StatementUploadResponse: {
      /** Format: uuid */
      upload_id?: string;
      /** Format: uuid */
      account_id?: string;
      file_name?: string;
      /** Format: date-time */
      upload_date?: string;
      status?: components["schemas"]["UploadStatus"];
      inserted_count?: number;
      skipped_duplicates?: components["schemas"]["SkippedTransactionDto"][];
    };
    UploadErrorLogResponse: {
      /** @enum {string} */
      error_type?: "MISSING_DATE_COLUMN" | "MISSING_AMOUNT_COLUMN" | "MISSING_REQUIRED_COLUMN" | "PARSE_ERROR" | "VALIDATION_ERROR";
      missing_columns?: string[] | null;
      error_detail?: string;
      /** Format: date-time */
      created_at?: string;
    };
    ListUploadsResponse: {
      uploads?: components["schemas"]["StatementUploadResponse"][];
    };
  };
  responses: never;
  parameters: {
    /** @description Unique identifier of the household resource */
    HouseholdId: string;
    /** @description Unique identifier of the account */
    AccountId: string;
    /** @description Unique identifier of the transaction */
    TxnId: string;
    /** @description Unique identifier of the statement upload */
    UploadId: string;
    /** @description Unique identifier of the physical asset */
    AssetId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export interface external {
  "shared.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: {
      schemas: {
        /**
         * @description ISO 4217 currency code. Currently INR only.
         * @default INR
         * @enum {string}
         */
        Currency: "INR";
        /** @description Standard error response body. Follows AIP-193 and Google error model. All 4xx and 5xx responses use this schema. */
        Error: {
          /**
           * @description HTTP status code mirrored in the body for client convenience.
           * @example 404
           */
          code: number;
          /**
           * @description Machine-readable error status string. Maps to gRPC status codes. Values: INVALID_ARGUMENT (400), NOT_FOUND (404), ALREADY_EXISTS (409), INTERNAL (500).
           *
           * @example NOT_FOUND
           * @enum {string}
           */
          status: "INVALID_ARGUMENT" | "NOT_FOUND" | "ALREADY_EXISTS" | "FAILED_PRECONDITION" | "INTERNAL";
          /**
           * @description Human-readable summary of the error. Suitable for display.
           * @example Profile not found
           */
          message: string;
          /** @description Field-level validation issues. Present on INVALID_ARGUMENT (400) errors. Empty or absent for all other error types. */
          details?: external["shared.yaml"]["components"]["schemas"]["ValidationIssue"][];
        };
        /** @description A single field-level validation failure within an error response. */
        ValidationIssue: {
          /**
           * @description Dot-notation path to the invalid field within the request body. Examples: "full_name", "account.credit_limit", "items[0].quantity".
           *
           * @example full_name
           */
          field: string;
          /**
           * @description Human-readable description of the constraint that was violated.
           * @example must not be blank
           */
          issue: string;
        };
      };
      responses: {
        /** @description 400 — Request body or query parameters failed validation. The 'details' array lists every field that violated a constraint. */
        BadRequest: {
          content: {
            "application/json": external["shared.yaml"]["components"]["schemas"]["Error"];
          };
        };
        /** @description 404 — The requested resource does not exist. */
        NotFound: {
          content: {
            "application/json": external["shared.yaml"]["components"]["schemas"]["Error"];
          };
        };
        /** @description 409 — The request conflicts with existing state. Examples: duplicate unique value, deactivating a resource with active children. */
        Conflict: {
          content: {
            "application/json": external["shared.yaml"]["components"]["schemas"]["Error"];
          };
        };
        /** @description 409 — A precondition for this operation was not met. Examples: uploading to a deactivated account, deleting an admin with active members. */
        FailedPrecondition: {
          content: {
            "application/json": external["shared.yaml"]["components"]["schemas"]["Error"];
          };
        };
        /** @description 500 — An unexpected server-side error occurred. The client should retry with exponential backoff. */
        InternalError: {
          content: {
            "application/json": external["shared.yaml"]["components"]["schemas"]["Error"];
          };
        };
      };
      parameters: {
        /** @description 0-indexed page number. Defaults to 0. */
        Page?: number;
        /** @description Maximum number of items to return per page. Defaults to 50, maximum 200. */
        Size?: number;
        /** @description Unique identifier of the household member profile. */
        ProfileIdParam: string;
        /** @description Unique identifier of the household member profile. Required on every list/scoped operation project-wide — no domain treats this as optional. */
        ProfileIdRequiredQueryParam: string;
      };
      requestBodies: never;
      headers: never;
      pathItems: never;
    };
    $defs: Record<string, never>;
  };
}

export interface operations {

  /**
   * List all accounts
   * @description Returns accounts optionally filtered by account_type, is_active, and profile_id. Follows AIP-132.
   */
  listAccounts: {
    parameters: {
      query: {
        account_type?: components["schemas"]["AccountType"];
        is_active?: boolean;
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ListAccountsResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Create an account
   * @description Creates a new financial account scoped to a profile. Follows AIP-133.
   */
  createAccount: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAccountRequest"];
      };
    };
    responses: {
      /** @description Account created */
      201: {
        content: {
          "application/json": components["schemas"]["AccountResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Get an account
   * @description Follows AIP-131.
   */
  getAccount: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
      path: {
        accountId: components["parameters"]["AccountId"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AccountResponse"];
        };
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Deactivate an account
   * @description Soft-deletes an account (is_active = false). Accounts with transactions cannot be deactivated. Follows AIP-135.
   */
  deactivateAccount: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
      path: {
        accountId: components["parameters"]["AccountId"];
      };
    };
    responses: {
      /** @description Account deactivated */
      204: {
        content: never;
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      409: external["shared.yaml"]["components"]["responses"]["Conflict"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Update an account
   * @description Partially updates an account. Only provided fields are updated. account_type and institution_name are immutable after creation. Follows AIP-134.
   */
  updateAccount: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
      path: {
        accountId: components["parameters"]["AccountId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAccountRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AccountResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Get the computed current balance for an account
   * @description opening_balance + SUM(CREDIT) - SUM(DEBIT) over the account's full transaction ledger (Epic 8 Phase 1, Bug 2 fix).
   */
  getAccountBalance: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
      path: {
        accountId: components["parameters"]["AccountId"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AccountBalanceResponse"];
        };
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Get current amortization summary for a loan account
   * @description Epic 8 Phase 3. Requires loan metadata set via PATCH /classification. Only valid for HOME_LOAN, CAR_LOAN, PERSONAL_LOAN accounts.
   */
  getAmortization: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
      path: {
        accountId: components["parameters"]["AccountId"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AmortizationSummaryResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Set Epic 8 classification metadata on an account
   * @description Merges category, liquidity_tier, purpose_tag, and joint_owners (ADR-016 Decision 2) into the account's existing metadata map. All fields optional.
   */
  updateAccountClassification: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
      path: {
        accountId: components["parameters"]["AccountId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAccountClassificationRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AccountResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * List transactions for an account
   * @description Returns transactions for the given account, optionally filtered by date range and transaction type. Follows AIP-132.
   */
  listTransactions: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
        /** @description Start date filter (inclusive), format YYYY-MM-DD. */
        from?: string;
        /** @description End date filter (inclusive), format YYYY-MM-DD. */
        to?: string;
        txn_type?: components["schemas"]["TransactionType"];
        /** @description 0-indexed page number. Defaults to 0. */
        page?: number;
        /** @description Page size. Defaults to 50, max 200. */
        size?: number;
      };
      path: {
        accountId: components["parameters"]["AccountId"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ListTransactionsResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Manually enter a single transaction
   * @description Creates a manually-entered transaction without a CSV upload (Q7). Tagged with metadata.source = "MANUAL". No dedup check.
   */
  createTransaction: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
      path: {
        accountId: components["parameters"]["AccountId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTransactionRequest"];
      };
    };
    responses: {
      /** @description Transaction created */
      201: {
        content: {
          "application/json": components["schemas"]["TransactionResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Get a transaction
   * @description Follows AIP-131.
   */
  getTransaction: {
    parameters: {
      path: {
        accountId: components["parameters"]["AccountId"];
        txnId: components["parameters"]["TxnId"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["TransactionResponse"];
        };
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Set the expense category on a single transaction
   * @description Epic 8 Phase 2 manual categorization (Use Case 8.3, Q24).
   */
  updateTransactionCategory: {
    parameters: {
      path: {
        accountId: components["parameters"]["AccountId"];
        txnId: components["parameters"]["TxnId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTransactionCategoryRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["TransactionResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Set the expense category on a caller-selected list of transactions
   * @description Epic 8 Phase 2 bulk-tag-by-selection (Use Case 8.3, Q24 resolution — not a rules engine). Tags every transaction_id in the request with the same category.
   */
  bulkUpdateTransactionCategory: {
    parameters: {
      path: {
        accountId: components["parameters"]["AccountId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkUpdateTransactionCategoryRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ListTransactionsResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * List uploads for an account
   * @description Follows AIP-132.
   */
  listUploads: {
    parameters: {
      path: {
        accountId: components["parameters"]["AccountId"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ListUploadsResponse"];
        };
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Upload a CSV bank statement
   * @description Parses and imports a CSV bank statement for the given account. Returns a statement upload record with status. Follows AIP-133.
   */
  uploadStatement: {
    parameters: {
      path: {
        accountId: components["parameters"]["AccountId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadStatementRequest"];
      };
    };
    responses: {
      /** @description Statement uploaded */
      201: {
        content: {
          "application/json": components["schemas"]["StatementUploadResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Get structured parse errors for a failed upload */
  getUploadErrors: {
    parameters: {
      path: {
        accountId: components["parameters"]["AccountId"];
        uploadId: components["parameters"]["UploadId"];
      };
    };
    responses: {
      /** @description Error entries for the upload */
      200: {
        content: {
          "application/json": components["schemas"]["UploadErrorLogResponse"][];
        };
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Rollback a statement upload
   * @description Deletes all transactions imported by this upload and removes the upload record. Follows AIP-135.
   */
  rollbackUpload: {
    parameters: {
      path: {
        accountId: components["parameters"]["AccountId"];
        uploadId: components["parameters"]["UploadId"];
      };
    };
    responses: {
      /** @description Upload rolled back */
      204: {
        content: never;
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * List all physical assets
   * @description Returns physical assets (vehicles, etc.) optionally filtered by asset_type, is_active, and profile_id. Follows AIP-132.
   */
  listPhysicalAssets: {
    parameters: {
      query: {
        asset_type?: components["schemas"]["AssetType"];
        is_active?: boolean;
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ListPhysicalAssetsResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Register a physical asset
   * @description Creates a new physical asset scoped to a profile. registration_number must be unique. Follows AIP-133.
   */
  createPhysicalAsset: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePhysicalAssetRequest"];
      };
    };
    responses: {
      /** @description Physical asset created */
      201: {
        content: {
          "application/json": components["schemas"]["PhysicalAssetResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      409: external["shared.yaml"]["components"]["responses"]["Conflict"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Get a physical asset
   * @description Follows AIP-131.
   */
  getPhysicalAsset: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
      path: {
        assetId: components["parameters"]["AssetId"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["PhysicalAssetResponse"];
        };
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Deactivate a physical asset
   * @description Soft-deletes a physical asset (is_active = false). Follows AIP-135.
   */
  deactivatePhysicalAsset: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
      path: {
        assetId: components["parameters"]["AssetId"];
      };
    };
    responses: {
      /** @description Physical asset deactivated */
      204: {
        content: never;
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Update a physical asset
   * @description Partially updates a physical asset. Only provided fields are updated. metadata is merged into the existing map, never replaced wholesale. asset_type and registration_number are immutable after creation. Follows AIP-134.
   */
  updatePhysicalAsset: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
      path: {
        assetId: components["parameters"]["AssetId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePhysicalAssetRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["PhysicalAssetResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** List calendar events for a profile */
  listCalendarEvents: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
        event_type?: string;
        from_date?: string;
        to_date?: string;
      };
    };
    responses: {
      /** @description Events returned */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Create a calendar event */
  createCalendarEvent: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Event created */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Get a calendar event */
  getCalendarEvent: {
    parameters: {
      path: {
        id: components["parameters"]["HouseholdId"];
      };
    };
    responses: {
      /** @description Event found */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Delete a calendar event */
  deleteCalendarEvent: {
    parameters: {
      path: {
        id: components["parameters"]["HouseholdId"];
      };
    };
    responses: {
      /** @description Event deleted */
      204: {
        content: never;
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Update a calendar event */
  updateCalendarEvent: {
    parameters: {
      path: {
        id: components["parameters"]["HouseholdId"];
      };
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Event updated */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** List inventory items for a profile */
  listInventoryItems: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
        source_platform?: string;
        category?: string;
      };
    };
    responses: {
      /** @description Items returned */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Add an inventory item */
  createInventoryItem: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Item added */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Get an inventory item */
  getInventoryItem: {
    parameters: {
      path: {
        id: components["parameters"]["HouseholdId"];
      };
    };
    responses: {
      /** @description Item found */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Update an inventory item
   * @description Full edit of an inventory item, including toggling is_consumed ("used in a calculation," not "physically used up"). Items are never deleted or expired.
   */
  updateInventoryItem: {
    parameters: {
      path: {
        id: components["parameters"]["HouseholdId"];
      };
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Item updated */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Delete an inventory item */
  deleteInventoryItem: {
    parameters: {
      path: {
        id: components["parameters"]["HouseholdId"];
      };
    };
    responses: {
      /** @description Item deleted */
      204: {
        content: never;
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** List financial goals for a profile */
  listGoals: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
        status?: string;
      };
    };
    responses: {
      /** @description Goals returned */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Create a financial goal */
  createGoal: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Goal created */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Get a goal */
  getGoal: {
    parameters: {
      path: {
        id: components["parameters"]["HouseholdId"];
      };
    };
    responses: {
      /** @description Goal found */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Delete a goal */
  deleteGoal: {
    parameters: {
      path: {
        id: components["parameters"]["HouseholdId"];
      };
    };
    responses: {
      /** @description Goal deleted */
      204: {
        content: never;
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Update a goal */
  updateGoal: {
    parameters: {
      path: {
        id: components["parameters"]["HouseholdId"];
      };
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Goal updated */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Trigger full projection refresh for a profile
   * @description Calls each domain service, computes cross-domain metrics, and writes results to projections.dashboard_snapshot via UPSERT. Synchronous — returns 200 once all snapshots are written.
   */
  refreshProjections: {
    parameters: {
      path: {
        profileId: string;
      };
    };
    responses: {
      /** @description Projections refreshed */
      200: {
        content: {
          "application/json": components["schemas"]["DashboardResponse"];
        };
      };
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Read pre-computed dashboard snapshots for a profile
   * @description Reads from projections.dashboard_snapshot — instant response with no re-computation. Returns an empty snapshots list if no refresh has run.
   */
  getDashboard: {
    parameters: {
      path: {
        profileId: string;
      };
    };
    responses: {
      /** @description Dashboard snapshots returned */
      200: {
        content: {
          "application/json": components["schemas"]["DashboardResponse"];
        };
      };
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Check trip budget against liquid savings and vehicle compliance against trip dates
   * @description Reads the profile's already-computed WEALTH_LIQUIDITY_TIERS_FAMILY snapshot (refresh the dashboard first if it does not exist yet) and compares the LIQUID tier balance to the trip cost. Separately checks every active VEHICLE physical asset's PUC/insurance expiry (read directly from JSONB metadata) against the trip end date.
   */
  vacationPlannerBudgetCheck: {
    parameters: {
      query: {
        profile_id: external["shared.yaml"]["components"]["parameters"]["ProfileIdRequiredQueryParam"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VacationPlannerRequest"];
      };
    };
    responses: {
      /** @description Budget and compliance check results */
      200: {
        content: {
          "application/json": components["schemas"]["VacationPlannerResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** List all admins */
  listAdmins: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ListAdminsResponse"];
        };
      };
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Create an admin */
  createAdmin: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAdminRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["AdminResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      409: external["shared.yaml"]["components"]["responses"]["Conflict"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Get an admin by id */
  getAdmin: {
    parameters: {
      path: {
        adminId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AdminResponse"];
        };
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Merge household policy settings (includes the one-time setup_completed flag)
   * @description Merges the provided keys into the admin's existing policy_settings map. Keys with a null value are ignored (existing value is preserved).
   */
  updateAdminPolicySettings: {
    parameters: {
      path: {
        adminId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAdminPolicyRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AdminResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** List profiles scoped to an admin */
  listProfiles: {
    parameters: {
      query?: {
        admin_id?: string;
        is_active?: boolean;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ListProfilesResponse"];
        };
      };
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Create a household member profile */
  createProfile: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProfileRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["ProfileResponse"];
        };
      };
      400: external["shared.yaml"]["components"]["responses"]["BadRequest"];
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      409: external["shared.yaml"]["components"]["responses"]["Conflict"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Get a profile by id */
  getProfile: {
    parameters: {
      path: {
        profileId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ProfileResponse"];
        };
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /** Deactivate a profile (soft delete) */
  deactivateProfile: {
    parameters: {
      path: {
        profileId: string;
      };
    };
    responses: {
      /** @description No content */
      204: {
        content: never;
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
  /**
   * Update a profile
   * @description Partial update. Only email_address, gender, blood_type, and is_active are mutable — full_name, dob, relation_to_admin, admin_id are immutable.
   */
  updateProfile: {
    parameters: {
      path: {
        profileId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ProfileResponse"];
        };
      };
      404: external["shared.yaml"]["components"]["responses"]["NotFound"];
      500: external["shared.yaml"]["components"]["responses"]["InternalError"];
    };
  };
}
