/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/accounts": {
    /**
     * List all accounts
     * @description Returns a paginated list of accounts. Supports filtering by account_type and is_active. Follows AIP-132 (Standard List) and AIP-158 (Pagination).
     */
    get: operations["listAccounts"];
    /**
     * Create an account
     * @description Creates a new account. Follows AIP-133 (Standard Create). The name field must be unique per institution.
     */
    post: operations["createAccount"];
  };
  "/v1/accounts/{account_id}": {
    /**
     * Get an account
     * @description Returns a single account by ID. Follows AIP-131 (Standard Get).
     */
    get: operations["getAccount"];
    /**
     * Deactivate an account
     * @description Soft deletes an account by setting is_active to false. Follows AIP-135 (Standard Delete). Accounts with transactions cannot be hard deleted.
     */
    delete: operations["deleteAccount"];
    /**
     * Update an account
     * @description Partially updates an account. Follows AIP-134 (Standard Update). Only fields present in the request body are updated. account_type and institution_name are immutable after creation.
     */
    patch: operations["updateAccount"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description Type of the account
     * @enum {string}
     */
    AccountType: "SAVINGS" | "CURRENT" | "CREDIT_CARD" | "HOME_LOAN" | "PERSONAL_LOAN" | "CAR_LOAN" | "MUTUAL_FUND" | "NPS" | "PPF" | "FD";
    /** @description Represents a financial account */
    Account: {
      /**
       * @description Resource name. Follows AIP-122. Format: accounts/{account_id}
       *
       * @example accounts/a1b2c3d4-e5f6-7890-abcd-ef1234567890
       */
      name?: string;
      /** Format: uuid */
      account_id?: string;
      /** @example HDFC Savings */
      account_name?: string;
      account_type?: components["schemas"]["AccountType"];
      /** @example HDFC Bank */
      institution_name?: string;
      /**
       * Format: double
       * @example 50000
       */
      opening_balance?: number;
      /**
       * Format: double
       * @description Calculated live from transactions
       */
      current_balance?: number;
      /**
       * Format: double
       * @description Applicable only for CREDIT_CARD accounts
       * @example 200000
       */
      credit_limit?: number | null;
      /**
       * Format: double
       * @description Remaining principal for loan accounts
       */
      loan_outstanding?: number | null;
      /**
       * Format: double
       * @description Annual interest rate percentage
       * @example 8.75
       */
      interest_rate?: number | null;
      /**
       * Format: double
       * @description Fixed monthly EMI for loan accounts
       */
      emi_amount?: number | null;
      /**
       * Format: double
       * @description Current market value for investment accounts
       */
      current_value?: number | null;
      /** @default true */
      is_active?: boolean;
      /** Format: date-time */
      created_at?: string;
    };
    CreateAccountRequest: {
      /** @example HDFC Savings */
      account_name: string;
      account_type: components["schemas"]["AccountType"];
      /** @example HDFC Bank */
      institution_name: string;
      /**
       * Format: double
       * @default 0
       */
      opening_balance?: number;
      /** Format: double */
      credit_limit?: number | null;
      /** Format: double */
      loan_outstanding?: number | null;
      /** Format: double */
      interest_rate?: number | null;
      /** Format: double */
      emi_amount?: number | null;
    };
    /** @description All fields optional. Only provided fields are updated. account_type and institution_name cannot be changed after creation. */
    UpdateAccountRequest: {
      account_name?: string;
      /** Format: double */
      opening_balance?: number;
      /** Format: double */
      credit_limit?: number | null;
      /** Format: double */
      loan_outstanding?: number | null;
      /** Format: double */
      interest_rate?: number | null;
      /** Format: double */
      emi_amount?: number | null;
      /** Format: double */
      current_value?: number | null;
      is_active?: boolean;
    };
    /** @description Paginated list of accounts. Follows AIP-158. */
    ListAccountsResponse: {
      accounts?: components["schemas"]["Account"][];
      /** @description Pass this as page_token in next request. Null means last page. */
      next_page_token?: string | null;
      /** @description Total number of accounts matching the filter */
      total_size?: number;
    };
    /** @description Standard error response. Follows AIP-193 and Google error model structure. */
    Error: {
      /**
       * @description HTTP status code
       * @example 404
       */
      code: number;
      /**
       * @description Error status string
       * @example NOT_FOUND
       */
      status: string;
      /**
       * @description Human readable error message
       * @example Account a1b2c3d4 not found
       */
      message: string;
      /** @description Additional error details */
      details?: {
          /** @example account_name */
          field?: string;
          /** @example must not be blank */
          issue?: string;
        }[];
    };
  };
  responses: {
    /** @description Request validation failed */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Resource not found */
    NotFound: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Resource already exists or has conflicting state */
    Conflict: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Unexpected server error */
    InternalError: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    /** @description Unique identifier of the account */
    AccountId: string;
    /** @description Maximum number of items to return. Follows AIP-158. Defaults to 20, maximum 100. */
    PageSize?: number;
    /** @description Token from previous response next_page_token. Omit for first page. */
    PageToken?: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * List all accounts
   * @description Returns a paginated list of accounts. Supports filtering by account_type and is_active. Follows AIP-132 (Standard List) and AIP-158 (Pagination).
   */
  listAccounts: {
    parameters: {
      query?: {
        page_size?: components["parameters"]["PageSize"];
        page_token?: components["parameters"]["PageToken"];
        account_type?: components["schemas"]["AccountType"];
        is_active?: boolean;
      };
    };
    responses: {
      /** @description Successfully listed accounts */
      200: {
        content: {
          "application/json": components["schemas"]["ListAccountsResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      500: components["responses"]["InternalError"];
    };
  };
  /**
   * Create an account
   * @description Creates a new account. Follows AIP-133 (Standard Create). The name field must be unique per institution.
   */
  createAccount: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAccountRequest"];
      };
    };
    responses: {
      /** @description Account created successfully */
      201: {
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      400: components["responses"]["BadRequest"];
      409: components["responses"]["Conflict"];
      500: components["responses"]["InternalError"];
    };
  };
  /**
   * Get an account
   * @description Returns a single account by ID. Follows AIP-131 (Standard Get).
   */
  getAccount: {
    parameters: {
      path: {
        account_id: components["parameters"]["AccountId"];
      };
    };
    responses: {
      /** @description Account found */
      200: {
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalError"];
    };
  };
  /**
   * Deactivate an account
   * @description Soft deletes an account by setting is_active to false. Follows AIP-135 (Standard Delete). Accounts with transactions cannot be hard deleted.
   */
  deleteAccount: {
    parameters: {
      path: {
        account_id: components["parameters"]["AccountId"];
      };
    };
    responses: {
      /** @description Account deactivated successfully */
      204: {
        content: never;
      };
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      500: components["responses"]["InternalError"];
    };
  };
  /**
   * Update an account
   * @description Partially updates an account. Follows AIP-134 (Standard Update). Only fields present in the request body are updated. account_type and institution_name are immutable after creation.
   */
  updateAccount: {
    parameters: {
      path: {
        account_id: components["parameters"]["AccountId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAccountRequest"];
      };
    };
    responses: {
      /** @description Account updated successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalError"];
    };
  };
}
