# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=filesystem:../../../../../../flyway/profile

# OpenAPI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
